[workspace]
name = "peluditOS"
version = "0.1.0"
edition = "2024"
resolver = "3"

# Define workspace members
members = [
    "crates/graphics",
    "crates/allocators",
]

exclude = [
    "boot"
]

[workspace.dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = { version = "0.10.0" }
pelu-graphics = { path = "crates/graphics" }
pelu-alloc = { path = "crates/allocators" }