[package]
name = "pelu_graphics"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
lazy_static.workspace = true
spin.workspace = true