[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = ["-C", "code-model=kernel", "-C", "relocation-model=static", "-C", "link-args=--script=link.ld --nostdlib --gc-sections"]