[unstable]
build-std = ["core", "compiler_builtins"]


[build]
target = "protected_mode.json"

[target.'cfg(target_arch = "x86")']
rustflags = ["-C", "code-model=kernel", "-C", "relocation-model=static", "-C", "link-args=--script=link.ld --nostdlib --gc-sections"]